# Generated by Django 6.0.6 on 2026-06-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('H', 'p1'), ('M', 'p2'), ('L', 'p3')], default='L', max_length=1),
        ),
    ]
