# Generated by Django 6.0.6 on 2026-06-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
